apiVersion: operator.knative.dev/v1beta1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: knative-operator
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: knative-operator-binding
subjects:
  - kind: ServiceAccount
    namespace: knative-serving
    name: knative-operator
roleRef:
  kind: ClusterRole
  name: knative-operator
  apiGroup: rbac.authorization.k8s.io
