apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: gitea-binding
spec:
  params:
    - name: repo-url
      value: ssh://git@git.apps.okd.sebbia.org:2222/Sebbia/dev.git
    - name: image-reference
      value: docker.io/froggyprogg/ci-cd