apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: tekton
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: tekton
  source: operatorhubio-catalog
  sourceNamespace: olm
