apiVersion: v1
kind: Secret
metadata:
  name: docker-credentials
data:
  config.json: ewoJImF1dGhzIjogewoJCSJkb2NrZXJwcml2YXRlLmFwcHMub2tkLnNlYmJpYS5vcmciOiB7CgkJCSJhdXRoIjogIlpHRjJhV1F1YW1Gc1lXZGhibWxoT2tadllXeHZNMFZwZHpSaFpXMTFZV2c9IgoJCX0sCgkJImh0dHBzOi8vaW5kZXguZG9ja2VyLmlvL3YxLyI6IHsKCQkJImF1dGgiOiAiWkROaFpHd3djbVE2UkhWa2RXeGhNakVoIgoJCX0KCX0KfQ==